### ISSUE TITLE
Problems with oblique text

### ISSUE THREAD

**Issue by toprak** [danpla/dpscreenocr#26]
Due to the nature of the program, it cannot detect oblique text or words, even if it detects it, it detects it incorrectly, an angled area selection can be beautiful.

**Comment by danpla** [comment]
Could you please attach an example image?

**Comment by toprak** [comment]
since it may be nsfw I cropped, I was having hard time that bikinis  bla
bla, was trying to ocr with freshly downloaded best data, but i could not
set correct area so yeah, there are many stuff like that so changing
rectangle would be nice.

**Comment by danpla** [comment]
The main problem with this image is not the rotation, but the font. Even if you fix the rotation manually, Tesseract will still not recognize the text, since the official English data was trained on more traditionally looking fonts such as Arial or Times. You will need to find third-party language data that was trained on fonts like the one in your image (or even do the training yourself, if you like).

**Comment by toprak** [comment]
@danpla yes I know, I threw this picture in a hurry, unfortunately I couldn't find a proper example, rotation change is still really important especially for those who want to ocr word by word, because you may have to ocr the whole sentence or paragraph because of the rotation problem.
