### ISSUE TITLE
Reading QR-Codes

### ISSUE THREAD

**Issue by Golddouble** [danpla/dpscreenocr#27]
Maybe you can add the possibility to read qr codes?

How should it work?
1. I have a QR-code on my Screen. For example this one:
![k20230129-150609](https://user-images.githubusercontent.com/13977359/215332171-77cb3bcf-47cd-47e6-af6c-d869e6f658c4.png)
2. I start dpScreenOCR
3. I click Alt+Q to catch the QR-Code
4. I find now the web-link behind the QR-code in my clipboard

What do you think? Thank you for your feedback.

**Comment by danpla** [comment]
While it's technically easy to add such a feature, I think it's out of the scope of this program:

* Since people use dpScreenOCR for text recognition, it's unlikely that someone will expect the program to recognize barcodes, or will install it for this specific purpose.
* It will not play well with the current interface. There are OCR-specific options (active languages and "Split text blocks") that have nothing to do with barcodes, but some user might still think that they somehow affect barcode scanning.
* The information encoded in a barcode is usually available next to the barcode itself in normal text form. This makes barcodes (and QR codes in particular) seldom useful on desktops, since you can just select the text or click the URL. And even if the text is not selectable (e.g. it comes from a scanned page), you can use regular OCR.

**Comment by Golddouble** [comment]
Thank you.

**Comment by danpla** [comment]
You're welcome.
