### ISSUE TITLE
Screenshots please

### ISSUE THREAD

**Issue by cvladan** [danpla/dpscreenocr#29]
Please provide a screenshot or a video link to help users better understand how the tool works, before the install app.

I have found a video, although not very well recorded: https://www.youtube.com/watch?v=DCbfp0zMJCk

... but several screenshots from the application would be much better.

**Comment by danpla** [comment]
The best way to learn the tool is to read the user manual, which comes with the program and is also available online.

I believe that the screenshot itself will not help much, since the program's interface is not that intuitive and by itself gives no hints about how to use the program. I will probably try to make it more friendly for those who use the program for the first time (like an introduction text with brief usage instructions, detailed help pop-ups, etc.), but for now it's better to read the manual.

**Comment by cvladan** [comment]
I think the UI is quite intuitive and very efficient, so I've taken screenshots just so people can get some information before they install, without having to read the manual. People are visual learners, and screenshots are perfect for a quick look at features.

![image](https://user-images.githubusercontent.com/1913156/218812744-b2a9fe6c-f5ef-4b27-bc00-28c9aeda1b3f.png)
![image](https://user-images.githubusercontent.com/1913156/218812779-a82ee651-689e-4b17-85c6-36456fe9ca8b.png)
![image](https://user-images.githubusercontent.com/1913156/218812811-3803db11-4757-42d8-91fb-b93fedb9e0e4.png)

**Comment by danpla** [comment]
The website now has a screenshot, so I guess I can close this issue.
