### ISSUE TITLE
Why do I not get version 1.3.0 vai Repo update?

### ISSUE THREAD

**Issue by Golddouble** [danpla/dpscreenocr#32]
I am a bit confused.

According to https://github.com/danpla/dpscreenocr/releases/tag/v1.3.0, version 1.3.0 is the latest version.

I have added the danpla Repo according to https://software.opensuse.org//download.html?project=home%3Adanpla&package=dpscreenocr:
With ...
```
echo 'deb http://download.opensuse.org/repositories/home:/danpla/Debian_10/ /' | sudo tee /etc/apt/sources.list.d/home:danpla.list
curl -fsSL https://download.opensuse.org/repositories/home:danpla/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_danpla.gpg > /dev/null
sudo apt update
sudo apt install dpscreenocr
```
... some moth ago. This has worked. 

But when I make this:
```
$ sudo apt install dpscreenocr
Package lists are read... Ready
Dependency tree is built.       
Status information is read.... Done
dpscreenocr is already the latest version (1.2.0-1).
0 updated, 0 reinstalled, 0 to remove and 0 not updated.
```

My expectation was, that I will get version 1.3.0

What do I miss?

Would appreciate some answer. Thank you.

**Comment by danpla** [comment]
Indeed, 1.2.0 is the latest version available on Debian 10 (Buster). The reason is that since v1.3.0, dpScreenOCR requires Tesseract >= 4.1.0 and CMake >= 3.16, while Debian 10 provides only [4.0.0](https://packages.debian.org/buster/tesseract-ocr) and [3.13](https://packages.debian.org/buster/cmake), respectively.

If you can get newer versions of Tesseract and CMake (e.g. by building them manually), you can build dpScreenOCR from the source.

**Comment by Golddouble** [comment]
I see thank you.

**Comment by danpla** [comment]
The website now provides a self-contained bundle in a TAR.XZ archive that should work on Buster and even older Debian versions.
